# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# Fichier principal de déclaration des routes de l'application.
# Les routes utilisant l'attribut #[Route] sont importées automatiquement.

controllers:
    resource: routing.controllers

# Route technique utilisée par Symfony Security pour traiter la connexion JWT.
# Cette route est interceptée par le firewall "login" avant d'atteindre un contrôleur.
api_login:
    path: /api/login
    methods: [POST]